name: Git Actions Build and Push to Gitea Repository
on:
#   push:
#     branches:
#         - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Docker Login to Gitea
        run: |
            docker login coder-harbor.hc.apac.bosch.com:5000 -u ${{ secrets.GITEA_REPOSITORY_USERNAME }} -p ${{ secrets.GITEA_REPOSITORY_PASSWORD }}
        
      - name: Docker Build and Push 
        run: |
            docker compose build 
            docker compose push 