name: Git Actions Build and Push to Gitea Repository
on:
  push:
    branches:
        - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Docker Login to Dockerhub
        run: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Docker Build and Push 
        run: |
            docker compose build 
            docker compose push 